name: Code Style

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check_formatting:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.0'

      - name: Check formatting
        run: swift format lint --recursive --strict .
